/**
 * Diff Store - Persists per-file diff records to JSON files for on-demand retrieval.
 *
 * Each session gets one JSON file at ~/.happy-next/diffs/{sessionId}.json.
 * Records are appended as diffs are generated by DiffProcessors.
 * The App can later fetch a specific record via the getDiffDetail RPC handler.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { configuration } from '@/configuration';
import { logger } from '@/ui/logger';

export interface DiffRecord {
    callId: string;
    agent: 'codex' | 'gemini' | 'claude';
    filePath: string;
    diff: string;
    additions: number;
    deletions: number;
    timestamp: number;
}

const diffsDir = join(configuration.happyHomeDir, 'diffs');

function ensureDiffsDir(): void {
    if (!existsSync(diffsDir)) {
        mkdirSync(diffsDir, { recursive: true });
    }
}

function getFilePath(sessionId: string): string {
    return join(diffsDir, `${sessionId}.json`);
}

/**
 * Save one or more diff records for a session.
 * Appends to the existing JSON array in the file.
 */
export function saveDiffRecords(sessionId: string, records: DiffRecord[]): void {
    if (records.length === 0) return;

    try {
        ensureDiffsDir();
        const filePath = getFilePath(sessionId);

        let existing: DiffRecord[] = [];
        if (existsSync(filePath)) {
            try {
                existing = JSON.parse(readFileSync(filePath, 'utf-8'));
            } catch {
                // Corrupted file, start fresh
                existing = [];
            }
        }

        existing.push(...records);
        writeFileSync(filePath, JSON.stringify(existing), 'utf-8');
        logger.debug(`[DiffStore] Saved ${records.length} record(s) for session ${sessionId}`);
    } catch (error) {
        logger.warn(`[DiffStore] Failed to save diff records:`, error);
    }
}

/**
 * Get a specific diff record by callId and filePath.
 */
export function getDiffDetail(
    sessionId: string,
    callId: string,
    filePath: string
): { diff: string; additions: number; deletions: number } | null {
    try {
        const file = getFilePath(sessionId);
        if (!existsSync(file)) return null;

        const records: DiffRecord[] = JSON.parse(readFileSync(file, 'utf-8'));
        const record = records.find((r) => r.callId === callId && r.filePath === filePath);
        if (!record) return null;

        return { diff: record.diff, additions: record.additions, deletions: record.deletions };
    } catch (error) {
        logger.warn(`[DiffStore] Failed to get diff detail:`, error);
        return null;
    }
}
